title: Megan Easton # your name (or website title) here
logo: "file:///Users/meganeaston/Desktop/Learning%20Data%20Analysis/LinkedIn%20&%20Resume%20Stuff/IMG_6884.jpeg" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst, Musician, & Loan Processor  <br><br>
  <a href="https://www.linkedin.com/in/megan-easton2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
