title: Megan Easton # your name (or website title) here
logo: "images/Green Yellow Circle Fried Chicken Logo.png" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst, Musician, & Loan Processor  <br><br>
  <a href="https://www.linkedin.com/in/megan-easton2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
